version: '3.8'

services:
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  flask-backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@flask_db:5432/postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_SERVICE=flask_db
    depends_on:
      - flask_db

  react-frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3001:80"  # Mapping external port 3001 to internal port 80

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - flask-backend
      - react-frontend

volumes:
  pgdata: {}
