apiVersion: v1
kind: ConfigMap
metadata:
  name: react-config
data:
  VITE_APP_FLASK_API_URL: "https://mocki.io/v1/7cbc4c9e-7208-4772-97b2-cc9a2da061c9" # Internal URL for Flask service in Kubernetes
  VITE_APP_GREETING: "welcome from Tanigai universe"
